# -*- coding: utf-8 -*-
"""GEN AI EXP 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuy_A1QXD7xII7isg5lFqzEuHyrJe1Tg
"""

!pip install -q transformers diffusers accelerate torch pillow matplotlib sentencepiece

import torch
import matplotlib.pyplot as plt

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from diffusers import StableDiffusionPipeline

print("Loading models...")

# -------------------------------
# Text Generation Model
# -------------------------------

text_model_name = "google/flan-t5-base"

text_tokenizer = AutoTokenizer.from_pretrained(text_model_name)
text_model = AutoModelForSeq2SeqLM.from_pretrained(text_model_name)

# -------------------------------
# Image Generation Model
# -------------------------------

device = "cuda" if torch.cuda.is_available() else "cpu"

image_generator = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
)

image_generator = image_generator.to(device)

print("Models loaded successfully!")
print("Device:", device)

# ============================================================
# EXPERIMENT 11
# AI-BASED CONTENT GENERATION SYSTEM
# ============================================================

topic = input("Enter a content topic: ")

# -------------------------------
# TEXT GENERATION
# -------------------------------

text_prompt = f"""
Write a short article of about 120 words on the topic:
{topic}

Include:
1. Introduction
2. Importance
3. Applications
"""

text_inputs = text_tokenizer(
    text_prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

text_outputs = text_model.generate(
    **text_inputs,
    max_new_tokens=180,
    do_sample=False
)

generated_text = text_tokenizer.decode(
    text_outputs[0],
    skip_special_tokens=True
)

# -------------------------------
# IMAGE GENERATION
# -------------------------------

image_prompt = f"""
A realistic high-quality illustration representing {topic},
professional digital art,
highly detailed,
4K quality.
"""

print("\nGenerating image...")

generated_image = image_generator(
    image_prompt,
    num_inference_steps=30
).images[0]
\
# Save image
generated_image.save(
    "generated_content_image.png"
)

# -------------------------------
# DISPLAY TEXT
# -------------------------------

print("\nGENERATED TEXT")
print("-" * 60)
print(generated_text)

# -------------------------------
# DISPLAY IMAGE
# -------------------------------

plt.figure(figsize=(8, 8))
plt.imshow(generated_image)
plt.axis("off")
plt.title("AI Generated Image")
plt.show()

print("\nImage saved as generated_content_image.png")