# -*- coding: utf-8 -*-
"""GEN AI EXP 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojo6tS5OTQZZFq2VqRFobA9UwdO7UMRR
"""

!pip install -q transformers accelerate torch

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    pipeline
)

print("Libraries loaded successfully!")

texts = [
    "The transformer model achieved excellent accuracy.",
    "Large Language Models are revolutionizing AI.",
    "The football team won the championship.",
    "The cricket match was exciting.",
    "Neural networks are widely used in deep learning.",
    "The player scored a brilliant goal.",
    "Machine learning improves decision making.",
    "The tennis tournament starts tomorrow."
]

labels = [
    1, 1, 0, 0,
    1, 0, 1, 0
]

# 0 = Sports
# 1 = Technology

print("Dataset created successfully!")
print("Number of examples:", len(texts))

model_name = "bert-base-uncased"

print("Loading BERT model...")

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

print("BERT model loaded successfully!")

encodings = tokenizer(
    texts,
    truncation=True,
    padding=True,
    max_length=128
)

print("Tokenization completed successfully!")

class DomainDataset(Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {
            key: torch.tensor(value[idx])
            for key, value in self.encodings.items()
        }

        item["labels"] = torch.tensor(
            self.labels[idx],
            dtype=torch.long
        )

        return item

    def __len__(self):
        return len(self.labels)


dataset = DomainDataset(
    encodings,
    labels
)

print("PyTorch dataset created successfully!")

training_args = TrainingArguments(
    output_dir="./fine_tuned_model",
    per_device_train_batch_size=2,
    num_train_epochs=3,
    logging_steps=1,
    save_strategy="no",
    report_to="none"
)

print("Training configuration ready!")

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset
)

print("Starting fine-tuning...")

trainer.train()

print("Fine-tuning completed successfully!")

trainer.save_model("./fine_tuned_model")
tokenizer.save_pretrained("./fine_tuned_model")

print("Fine-tuned model saved successfully!")

classifier = pipeline(
    "text-classification",
    model="./fine_tuned_model",
    tokenizer="./fine_tuned_model"
)

text = "Generative AI models improve intelligent automation."

result = classifier(text)

labels_map = {
    "LABEL_0": "Sports",
    "LABEL_1": "Technology"
}

print("\nPrediction")
print("-------------------------")
print("Input :", text)
print(
    "Predicted Class :",
    labels_map[result[0]["label"]]
)
print(
    "Confidence Score :",
    round(result[0]["score"], 3)
)