# -*- coding: utf-8 -*-
"""GEN AI EXP 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVJy8ns2w4md8C9B1-h6n4VK-EeekcPp
"""

!pip install -q "transformers==4.44.2" "tokenizers==0.19.1" sentencepiece accelerate

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

print("Loading CodeT5 model...")

model_name = "Salesforce/codet5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

model = model.to(device)

print("CodeT5 Model Loaded Successfully!")
print("Device:", device)