# -*- coding: utf-8 -*-
"""GEN AI EXP 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ll6edXsam87cX2Nl1SNrB2etoXLniOu
"""

!pip install -q diffusers transformers accelerate torch pillow matplotlib

import torch
import matplotlib.pyplot as plt
from diffusers import StableDiffusionPipeline

print("Loading Stable Diffusion model...")

model_id = "runwayml/stable-diffusion-v1-5"

device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
)

pipe = pipe.to(device)

print("Stable Diffusion model loaded successfully!")
print("Device:", device)

prompt = """
A futuristic smart city with flying cars,
green buildings, robots assisting people,
highly detailed, realistic, 4K quality.
"""

print("Generating image...")

image = pipe(
    prompt,
    num_inference_steps=30
).images[0]

# Save image
image.save("generated_image.png")

# Display image
plt.figure(figsize=(8, 8))
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()

print("Image successfully generated and saved as generated_image.png")